name: "Create Robots.txt"
description: "An action to generate a robots.txt file"
author: "Stuart Thomson"

branding:
  icon: "file-text"
  color: "green"

inputs:
  output-file:
    description: "Where to write the resulting robots.txt file"
    default: "robots.txt"
  input-file:
    description: "An existing robots.txt. Will be added to the top of the output file. Must not be the same as the `output-file`"

outputs: {}

runs:
  using: node20
  main: dist/index.js
