# Unordered list style
MD004:
  style: dash

# Line length
# Disabled because of tables.
MD013: false

# Multiple heading with same content
# Disabled because of CHANGELOG format
MD024: false

# Ordered list item prefix
MD029:
  style: one

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# Code block style
MD046:
  style: fenced
